import { FACINGS, sanitizeDisplayName, type BlockSound, type Piece, type PieceJavaStates, type Project, type Version } from "@blockshop/schema";
import { blockIdentifier } from "./block.js";
import { javaModelPath } from "./java-model.js";

/** Folder under plugins/CraftEngine/resources/ that Blockshop owns completely. */
export const CRAFTENGINE_PACK_FOLDER = "blockshop";
export const CRAFTENGINE_CONFIG_FILE = "configuration/blockshop.json";
/** Namespace of what every profile shares (the catalog item) and the pack's default namespace. Never a profile id. */
export const SHARED_NAMESPACE = "blockshop";

const JAVA_SOUND_GROUP: Record<BlockSound, string> = { wood: "wood", stone: "stone", cloth: "wool", glass: "glass", metal: "metal" };
const JAVA_TOOL_TAG: Partial<Record<BlockSound, string>> = {
  wood: "minecraft:mineable/axe", stone: "minecraft:mineable/pickaxe", metal: "minecraft:mineable/pickaxe",
};

/** Item id suffix of the furniture catalog (the menu opener); `blockshop:catalog`. */
export const CATALOG_ID = "catalog";
export const CATALOG_NAME = "Furniture catalog";

export function catalogItemId(): string {
  return `${SHARED_NAMESPACE}:${CATALOG_ID}`;
}

export interface CraftEngineEntry {
  project: Project;
  piece: Piece;
  states: PieceJavaStates;
  sound: BlockSound;
}

/** One profile's pack and its pieces, as the merged CraftEngine config sees them. */
export interface CraftEngineProfile {
  project: Project;
  entries: readonly CraftEngineEntry[];
}

/** CraftEngine names are MiniMessage: drop its tag characters, keep the name upright (`<!i>`). */
export function miniMessageName(name: string, fallback: string): string {
  return "<!i>" + sanitizeDisplayName(name.replace(/[<>]/g, ""), fallback);
}

/** Seat position for `seat_block`: `x,y,z` in blocks relative to the block; y from the seat height plus the tuning offset. */
export function seatY(height: number, offset: number): string {
  return String(Math.round((height / 16 + offset) * 10000) / 10000);
}

export function buildPackYml(version: Version, pieceCount: number): string {
  const v = version.join(".");
  return [
    `# Generated by Blockshop (family server export v${v}); every update replaces this folder. Do not edit by hand.`,
    "author: Blockshop",
    `version: "${v}"`,
    `description: "Blockshop server export v${v} - ${pieceCount} piece${pieceCount === 1 ? "" : "s"}"`,
    `namespace: ${SHARED_NAMESPACE}`,
    "",
  ].join("\n");
}

/**
 * One CraftEngine item per piece with the block defined inline (`block_item`): a `paper` item with
 * the piece's 3D model, placing a leaves-backed custom block with four facings. Every profile's pieces
 * land in this one config (ids are namespaced per profile), with one browser category per profile.
 * JSON is one of the config formats CraftEngine loads; it avoids YAML quoting rules for kid-typed names.
 */
export function buildCraftEngineConfig(profiles: readonly CraftEngineProfile[]) {
  const items: Record<string, unknown> = {};
  const categories: Record<string, unknown> = {};
  profiles.forEach(({ project, entries }, index) => {
    for (const e of entries) {
      const id = blockIdentifier(project, e.piece.id);
      const model = javaModelPath(project.namespace, e.piece.id);
      const appearances: Record<string, unknown> = {};
      const variants: Record<string, unknown> = {};
      for (const f of FACINGS) {
        appearances[f] = { state: e.states[f], model: { path: model, y: project.java.yaw[f] } };
        variants[`facing=${f}`] = { appearance: f };
      }
      const group = JAVA_SOUND_GROUP[e.sound];
      const settings: Record<string, unknown> = {
        hardness: 0.6,
        resistance: 2,
        sounds: {
          break: `minecraft:block.${group}.break`, step: `minecraft:block.${group}.step`, place: `minecraft:block.${group}.place`,
          hit: `minecraft:block.${group}.hit`, fall: `minecraft:block.${group}.fall`,
        },
        item: id,
      };
      const tag = JAVA_TOOL_TAG[e.sound];
      if (tag) settings["tags"] = [tag];
      if (e.piece.options.light) settings["luminance"] = e.piece.options.light;
      const block: Record<string, unknown> = {
        states: {
          properties: { facing: { type: "horizontal_direction", default: "south" } },
          appearances,
          variants,
        },
        settings,
        loot: { template: "default:loot_table/self" },
      };
      const seat = e.piece.options.seat;
      if (seat?.enabled) block["behavior"] = { type: "seat_block", seats: [`0,${seatY(seat.height, project.java.seatOffset)},0`] };
      items[id] = {
        material: "paper",
        // Forced rather than left to CraftEngine's auto-derivation: the Geyser item mapping keys on this value.
        item_model: id,
        model,
        data: { item_name: miniMessageName(e.piece.name, e.piece.id) },
        behavior: { type: "block_item", block },
      };
    }
    // The `/ce` item browser is where vanilla Java clients find custom items: one category per profile with its visible pieces.
    const visible = entries.filter((e) => e.piece.options.hidden !== true);
    if (visible.length) {
      categories[`${project.namespace}:furniture`] = {
        name: miniMessageName(project.packName, "Furniture"),
        icon: blockIdentifier(project, visible[0]!.piece.id),
        priority: index,
        source: { type: "list", list: visible.map((e) => blockIdentifier(project, e.piece.id)) },
      };
    }
  });
  // The catalog item: selecting it opens the BlockshopCatalog menu (plugin); right-clicking it on Java opens
  // CraftEngine's browser even without the plugin. A plain paper with a generated flat icon.
  items[catalogItemId()] = {
    material: "paper",
    item_model: catalogItemId(),
    texture: `${SHARED_NAMESPACE}:item/${CATALOG_ID}`,
    data: { item_name: `<!i>${CATALOG_NAME}`, max_stack_size: 1 },
    events: [{ on: "right_click", functions: [{ type: "command", command: "ce item browser <arg:player.name>" }] }],
  };
  return { items, categories };
}
