import type { Project } from "@blockshop/schema";
import { seatComponentName } from "./block.js";

export function seatEntityId(namespace: string): string {
  return `${namespace}:seat`;
}

/**
 * Entity files are pinned to a format version whose component set is verified against a
 * vanilla file (armor_stand.json at 1.26.0 uses collision_box, physics, pushable, persistent,
 * knockback_resistance, type_family). At 1.26.20 Mojang replaced `minecraft:pushable` with
 * `pushable_by_entity`/`pushable_by_block`; an unknown component makes Minecraft drop the whole
 * entity, and the seat script then fails with "'family:seat' is not a valid entity type"
 * (seen on device 2026-09-14). Do not tie this to project.formatVersion.
 */
export const ENTITY_FORMAT_VERSION = "1.26.0";
/** Client entity format; 1.10.0 is the long-standing stable shape for a render-nothing entity. */
export const CLIENT_ENTITY_FORMAT_VERSION = "1.10.0";

export function buildSeatEntity(project: Project) {
  return {
    format_version: ENTITY_FORMAT_VERSION,
    "minecraft:entity": {
      description: { identifier: seatEntityId(project.namespace), is_spawnable: false, is_summonable: true },
      components: {
        "minecraft:type_family": { family: [`${project.namespace}_seat`, "inanimate"] },
        // A real hitbox: touch controls and the crosshair must be able to target the seat.
        "minecraft:collision_box": { width: 0.6, height: 0.5 },
        "minecraft:physics": { has_gravity: false, has_collision: true },
        "minecraft:pushable": { is_pushable: false, is_pushable_by_piston: false },
        "minecraft:damage_sensor": { triggers: [{ cause: "all", deals_damage: "no" }] },
        "minecraft:knockback_resistance": { value: 1.0 },
        "minecraft:fire_immune": {},
        // Seats live as long as their chair; the script removes orphans.
        "minecraft:persistent": {},
        "minecraft:rideable": {
          seat_count: 1,
          family_types: ["player"],
          interact_text: "action.interact.sit",
          crouching_skip_interact: true,
          pull_in_entities: false,
          seats: [{ position: [0, 0, 0] }],
        },
      },
    },
  };
}

export function buildSeatClientEntity(project: Project) {
  return {
    format_version: CLIENT_ENTITY_FORMAT_VERSION,
    "minecraft:client_entity": {
      description: {
        identifier: seatEntityId(project.namespace),
        materials: { default: "entity_alphatest" },
        textures: { default: `textures/entity/${project.namespace}_seat` },
        geometry: { default: `geometry.${project.namespace}.seat` },
        // Minecraft requires at least one render controller ("Array too small (0 < 1)" on device);
        // this one renders the empty geometry, so the seat stays invisible.
        render_controllers: [seatRenderControllerId(project.namespace)],
      },
    },
  };
}

export function buildSeatGeometry(project: Project) {
  return {
    format_version: "1.16.0",
    "minecraft:geometry": [
      { description: { identifier: `geometry.${project.namespace}.seat`, texture_width: 16, texture_height: 16 }, bones: [{ name: "root", pivot: [0, 0, 0] }] },
    ],
  };
}

export function seatRenderControllerId(namespace: string): string {
  return `controller.render.${namespace}_seat`;
}

export function buildSeatRenderController(project: Project) {
  return {
    format_version: "1.10.0",
    render_controllers: {
      [seatRenderControllerId(project.namespace)]: {
        geometry: "Geometry.default",
        materials: [{ "*": "Material.default" }],
        textures: ["Texture.default"],
      },
    },
  };
}

/**
 * Script module (custom components v2). Every placed seat-enabled block owns one invisible,
 * persistent, rideable seat entity at its seat height: on touch controls a tap on a block in a
 * creative world breaks it, but a tap on a rideable entity mounts it (or shows the ride button).
 * The entity is created on place and on every 5-second tick (self-healing), removed on destroy
 * and by a sweep for orphans. onPlayerInteract still mounts directly for mouse/controller.
 */
export function buildSeatScript(project: Project): string {
  const ns = project.namespace;
  return `// Generated by Blockshop. Requires @minecraft/server ${project.scriptApiVersion}.
import { system, world } from "@minecraft/server";

const SEAT_ENTITY = ${JSON.stringify(seatEntityId(ns))};
const COMPONENT = ${JSON.stringify(seatComponentName(ns))};
const BLOCK_PREFIX = ${JSON.stringify(ns + ":")};
const DIMENSIONS = ["overworld", "nether", "the_end"];

function seatHeight(p) {
  const params = (p && p.params) || {};
  return (typeof params.height === "number" ? params.height : 8) / 16;
}
function seatLocation(block, height) {
  const { x, y, z } = block.location;
  return { x: x + 0.5, y: y + height, z: z + 0.5 };
}
function seatsNear(dimension, location, maxDistance) {
  try { return dimension.getEntities({ type: SEAT_ENTITY, location, maxDistance }); } catch { return []; }
}
let spawnFailureReported = false;
function ensureSeat(block, dimension, height) {
  const location = seatLocation(block, height);
  const existing = seatsNear(dimension, location, 0.4);
  if (existing.length > 0) return existing[0];
  try {
    return dimension.spawnEntity(SEAT_ENTITY, location);
  } catch (err) {
    if (!spawnFailureReported) {
      spawnFailureReported = true;
      console.warn("[Blockshop] cannot spawn " + SEAT_ENTITY + ": " + err + ". Is entities/seat.json valid for this Minecraft version?");
    }
    return undefined;
  }
}
function removeSeat(seat) {
  const rideable = seat.getComponent("minecraft:rideable");
  if (rideable) rideable.ejectRiders();
  seat.remove();
}

system.beforeEvents.startup.subscribe((init) => {
  init.blockComponentRegistry.registerCustomComponent(COMPONENT, {
    onPlace(e, p) { ensureSeat(e.block, e.dimension, seatHeight(p)); },
    onTick(e, p) { ensureSeat(e.block, e.dimension, seatHeight(p)); },
    onPlayerDestroy(e) {
      const { x, y, z } = e.block.location;
      for (const seat of seatsNear(e.dimension, { x: x + 0.5, y: y + 0.5, z: z + 0.5 }, 1.0)) removeSeat(seat);
    },
    onPlayerInteract(e, p) {
      const player = e.player;
      if (!player) return;
      const seat = ensureSeat(e.block, e.dimension, seatHeight(p));
      const rideable = seat ? seat.getComponent("minecraft:rideable") : undefined;
      if (rideable) rideable.addRider(player);
    },
  });
});

// Sweep: a seat whose block is no longer furniture is an orphan.
system.runInterval(() => {
  for (const dimensionId of DIMENSIONS) {
    let dimension;
    try { dimension = world.getDimension(dimensionId); } catch { continue; }
    let seats;
    try { seats = dimension.getEntities({ type: SEAT_ENTITY }); } catch { continue; }
    for (const seat of seats) {
      let block;
      try { block = dimension.getBlock(seat.location); } catch { block = undefined; }
      if (block === undefined) continue; // chunk not loaded: leave it
      if (!block.typeId.startsWith(BLOCK_PREFIX)) removeSeat(seat);
    }
  }
}, 100);
`;
}
